
'use strict';
const {rows,meta}=await window.parent.dashboardLoad();const $=id=>document.getElementById(id);
for(const r of rows){for(const prefix of ['projected_','actual_']){const pa=r[prefix+'PA'],hr=r[prefix+'HR'];r[prefix+'HR_per_PA']=r.model_role==='Hitter'&&Number.isFinite(pa)&&pa>0&&Number.isFinite(hr)?100*hr/pa:null;}}
const explanations={},skillDefs=meta.skill_definitions;
const outcomeLabel=k=>({HRA:'HR allowed',HR_TBF_pct:'HR/TBF',K_pct:'K%',BB_pct:'BB%',K_minus_BB_pct:'K−BB%',OPS:'OPS (est.)'}[k]||k);
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const common=[['roster_player_name','Player'],['roster_team_name','Team'],['roster_entry_type','Roster status'],['roster_position','Pos'],['model_role','Model'],['roster_role','Depth-chart role']];
const hit=[...['PA','AB','H','R','HR','RBI','SB','AVG'].map(s=>['projected_'+s,s]),['projected_OPS','OPS (est.)'],['projected_HR_per_PA','HR/PA'],['projected_hitter_BB_pct','BB%'],['projected_hitter_K_pct','K%']];
const pitch=[...['IP','K','W','SV','ERA','WHIP'].map(s=>['projected_'+s,s]),['projected_K_pct','K%'],['projected_BB_pct','BB%'],['projected_K_minus_BB_pct','K−BB%'],['projected_HRA','HR allowed'],['projected_HR_TBF_pct','HR/TBF']];
const control=[['roster_target_season_contract','Target contract'],['fa_display','FA year / scenarios'],['roster_free_agent_year_status','FA status'],['roster_options_remaining_source','MiLB options'],['roster_contract_options','Contract options']];
const columns={all:[...common,...hit.filter(c=>!['AB','H'].includes(c[1])),...pitch,...control],hit:[...common,...hit,['sample_size','Source sample'],['sample_size_type','Unit'],['projection_coverage','Coverage']],pitch:[...common,...pitch,['projected_TBF','TBF'],['projected_BB','BB'],['projected_HA','H allowed'],['projected_ER','ER'],['sample_size','Source sample'],['sample_size_type','Unit']],control:[...common,...control,['roster_last_guaranteed_season','Last guaranteed'],['roster_control_notes','Control notes'],['roster_membership_agreement','MLB / RR agreement'],['projection_coverage','Projection']]};
const faFields=['roster_free_agent_year','roster_free_agent_year_if_options_declined','roster_free_agent_year_if_options_exercised','roster_earliest_opt_out_free_agent_year'];
function faText(r){const p=[];if(r.roster_free_agent_year!=null)p.push(r.roster_free_agent_year+(String(r.roster_free_agent_year_status).includes('conditional')?' conditional':''));if(r.roster_free_agent_year_if_options_declined!=null)p.push(r.roster_free_agent_year_if_options_declined+' declined');if(r.roster_free_agent_year_if_options_exercised!=null)p.push(r.roster_free_agent_year_if_options_exercised+' exercised');if(r.roster_earliest_opt_out_free_agent_year!=null)p.push(r.roster_earliest_opt_out_free_agent_year+' opt-out');return p.join(' / ')||'Not listed';}
rows.forEach((r,i)=>{r.fa_display=faText(r);r._index=i;});
function fmt(k,v){if(v==null||v==='')return '—';if(typeof v==='number'){if(k.endsWith('_HR_per_PA')||k.endsWith('_HR_TBF_pct'))return v.toFixed(2)+'%';if(k==='actual_season')return String(v);if(['projected_hitter_BB_pct','projected_hitter_K_pct','actual_hitter_BB_pct','actual_hitter_K_pct','projected_K_pct','projected_BB_pct','projected_K_minus_BB_pct','actual_K_pct','actual_BB_pct','actual_K_minus_BB_pct'].includes(k))return v.toFixed(1)+'%';if(k.endsWith('_AVG')||k.endsWith('_OPS'))return v.toFixed(3);if(k.endsWith('_ERA')||k.endsWith('_WHIP'))return v.toFixed(2);if(k.startsWith('projected_')||k.startsWith('actual_')||k==='roster_age')return v.toFixed(1);}return String(v);}
function visibleColumns(){if($('display').value!=='skills'||view==='control')return columns[view];const defs=skillDefs.filter(d=>view==='hit'?d.role==='Hitter':view==='pitch'?d.role==='Pitcher':true);return [...common,...defs.map(d=>[d.field,d.label+' ('+d.unit+')'])];}
function fill(id,values){[...new Set(values.filter(v=>v!=null&&v!==''))].sort((a,b)=>typeof a==='number'?a-b:String(a).localeCompare(String(b))).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;$(id).append(o);});}
fill('team',rows.map(r=>r.roster_team_name));fill('depth',rows.map(r=>r.roster_role));fill('fa',rows.flatMap(r=>faFields.map(k=>r[k])));fill('options',rows.map(r=>r.roster_options_remaining));
$('subtitle').textContent=`${meta.projection_season} projections • Statistics through ${meta.projection_data_through} • Rosters observed ${meta.roster_date}`;
$('projectedSeason').innerHTML=(meta.available_projection_seasons||[meta.projection_season]).map(y=>`<option value="${y}">${y}${y<meta.projection_season?' — retrospective':''}</option>`).join('');
function updateEnvironment(){const year=Number($('projectedSeason').value);const env=year===meta.projection_season?meta.league_environment:meta.retrospective?.environments?.[year];
if(env){const e=env.achieved;$('environmentSummary').innerHTML=`<strong>${esc(env.name)}</strong> · Complete league: <strong>${e.OPS.toFixed(3)} OPS</strong> (${e.OBP.toFixed(3)} OBP + ${e.SLG.toFixed(3)} SLG) · ${e.AVG.toFixed(3)} AVG · ${e.BB_pct.toFixed(2)}% BB · ${e.K_pct.toFixed(2)}% K<br>${Math.round(e.PA).toLocaleString()} PA, including ${Math.round(env.newcomer_PA).toLocaleString()} anonymous newcomer PA · ${Math.round(e.R).toLocaleString()} runs · Named-player pool: ${env.named_only.OPS.toFixed(3)} OPS. League totals include newcomers; roster filters do not redefine the environment. <a href="${year===meta.projection_season?'anonymous_newcomers.parquet':'retrospective_newcomers.parquet'}" download>Newcomer assumptions</a>`;}
$('subtitle').textContent=`${year} projections • Inputs through ${year-1} • Current roster snapshot: ${meta.roster_date}`;
$('footer').textContent=year<meta.projection_season?'Retrospective forecasts use pre-target model fits, workloads and league environments. Current team and contract labels are not historical assignments.':'Current projections. Missing measurements and forecasts remain unavailable.';}
updateEnvironment();
$('freshness').textContent=meta.external_source_freshness?.status==='waiting_for_completed_pull'?'Source refresh pending: Py_Damage files changed after its completion marker. This view uses the last validated full-season snapshot.':meta.external_source_freshness?.status==='new_completed_source_available'?'New source data is available; this view remains tied to its labeled, validated projection snapshot.':'';
$('metrics').innerHTML=[[meta.roster_players,'40-man players'],[meta.teams,'MLB teams'],[meta.players_with_projection,'Players projected'],[meta.players_without_projection,'Projection unavailable']].map(([n,l])=>`<div class="metric"><strong>${n.toLocaleString()}</strong><span>${l}</span></div>`).join('');
$('footer').textContent=`Model training: ${meta.projection_training_seasons.join(', ')}. Missing players have no forecast in the established MLB process-stat model. Salary amounts are not available in this roster export.`;
let view='all',sortKey='roster_team_name',sortDir=1,filtered=[];
let detailPlayer=null;
function positionEligible(r){return window.parent.projectionEligiblePositions?.(r.mlbam_id,r.model_role==='Hitter'?'Hitter':r.model_role?'Pitcher':null,Number(r.season)-1)||[];}
function updatePositions(){const selected=$('position').value,year=Number($('projectedSeason').value)-1;const choices=new Set(rows.filter(r=>Number(r.season)===year+1).flatMap(positionEligible));$('position').innerHTML='<option value="">All positions</option>'+(window.parent.projectionPositionOptions||[]).filter(p=>choices.has(p)).map(p=>'<option value="'+p+'">'+p+'</option>').join('');$('position').value=choices.has(selected)?selected:'';$('positionEligibilityNote').textContent=window.parent.projectionPositionNote?.(year)||'Position eligibility unavailable.';}
function render(){updatePositions();updateEnvironment();const seasonRows=rows.filter(r=>Number(r.season)===Number($('projectedSeason').value));const availableCount=new Set(seasonRows.filter(r=>r.projection_coverage==='Available').map(r=>r.mlbam_id)).size;$('metrics').innerHTML=[[meta.roster_players,'Current 40-man players'],[meta.teams,'Current MLB teams'],[availableCount,'Players projected'],[new Set(seasonRows.map(r=>r.mlbam_id)).size-availableCount,'Projection unavailable']].map(([n,l])=>`<div class="metric"><strong>${n.toLocaleString()}</strong><span>${l}</span></div>`).join('');$('skillViewNote').hidden=$('display').value!=='skills';const query=$('search').value.trim().toLowerCase();filtered=rows.filter(r=>{
if(Number(r.season)!==Number($('projectedSeason').value))return false;
if(query&&!`${r.roster_player_name} ${r.mlbam_id}`.toLowerCase().includes(query))return false;
if($('membership').value&&r.roster_entry_type!==$('membership').value)return false;
if($('team').value&&r.roster_team_name!==$('team').value)return false;
if($('position').value&&!positionEligible(r).includes($('position').value))return false;
if($('role').value&&($('role').value==='Unavailable'?r.model_role!=null:r.model_role!==$('role').value))return false;
if($('depth').value&&r.roster_role!==$('depth').value)return false;
if($('coverage').value&&r.projection_coverage!==$('coverage').value)return false;
if($('fa').value&&($('fa').value==='unknown'?faFields.some(k=>r[k]!=null):!faFields.some(k=>String(r[k])===$('fa').value)))return false;
if($('options').value&&($('options').value==='unknown'?r.roster_options_remaining!=null:String(r.roster_options_remaining)!==$('options').value))return false;
if(view==='hit'&&r.model_role!=='Hitter')return false;if(view==='pitch'&&!['SP','RP'].includes(r.model_role))return false;return true;});
filtered.sort((a,b)=>{const x=a[sortKey],y=b[sortKey];if(x==null)return y==null?0:1;if(y==null)return -1;return sortDir*(typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y)));});
$('head').innerHTML='<tr>'+visibleColumns().map(([k,l])=>`<th data-key="${k}">${esc(l)}${sortKey===k?(sortDir===1?' ↑':' ↓'):''}</th>`).join('')+'</tr>';
$('body').innerHTML=filtered.map(r=>'<tr>'+visibleColumns().map(([k])=>`<td class="${k==='roster_player_name'?'name':typeof r[k]==='number'?'':'text'} ${r.projection_coverage!=='Available'?'missing':''}" title="${esc(fmt(k,r[k]))}" ${k==='roster_player_name'?`data-player="${r._index}" tabindex="0" role="button"`:''}>${esc(fmt(k,r[k]))}</td>`).join('')+'</tr>').join('');
$('shown').textContent=`${new Set(filtered.map(r=>r.mlbam_id)).size.toLocaleString()} players · ${filtered.length.toLocaleString()} role rows`;
}
async function detail(index){const r=rows[index];const explanationKey=`${r.mlbam_id}:${r.model_role}:${r.season}`;if(meta.lazy_explanations&&!explanations[explanationKey]){try{const response=await window.parent.dashboardFetch(`explanations/${r.mlbam_id}_${r.model_role}_${r.season}.json`);if(response.ok)explanations[explanationKey]=await response.json();}catch(error){console.warn('Explanation unavailable',error);}}$('detailName').textContent=r.roster_player_name;$('detailContext').textContent=`${r.season} projection · ${r.roster_team_name||'Non-roster'} · ${r.roster_entry_type||'40-man'} · MLB ${r.mlbam_id} · ${r.model_role||'Projection unavailable'} · ${r.roster_role||'Role unavailable'}`;
detailPlayer=r;
setupParkScenario(r);
const available=explanations[`${r.mlbam_id}:${r.model_role}:${r.season}`]||{};
const outcomeOrder=r.model_role==='Hitter'?['HR','R','RBI','SB','AVG','OPS','H','AB']:['HRA','HR_TBF_pct','K','K_pct','BB_pct','K_minus_BB_pct','ERA','WHIP','IP','W','BB','HA','ER','TBF'];
$('explainOutcome').innerHTML=outcomeOrder.filter(k=>available[k]).map(k=>`<option value="${k}">${outcomeLabel(k)}</option>`).join('');
$('explanationPanel').hidden=!Object.keys(available).length;
$('detailSkills').innerHTML='<p class="note">Season-standardized next-season skill forecasts, converted to the selected reference distribution. Positive z means more of the measured skill, not necessarily better. Projected pulled FB% additionally informs the 2025–2027 HR adjustment; other skills are not directly substituted into the historical-skill outcome model. — means no recent measurement.</p><table><tr><th>Skill</th><th>'+r.season+' forecast</th><th>Seasonal z</th><th>Unit</th></tr>'+skillDefs.filter(d=>d.role===(r.model_role==='Hitter'?'Hitter':'Pitcher')).map(d=>`<tr><td>${esc(d.label)}</td><td>${esc(fmt(d.field,r[d.field]))}</td><td>${r[d.field+'_z']==null?'—':r[d.field+'_z'].toFixed(2)}</td><td>${esc(d.unit)}</td></tr>`).join('')+'</table>';
drawExplanation();
const stats=r.model_role==='Hitter'?hit:r.model_role?[...pitch,['projected_HA','H allowed'],['projected_BB','BB'],['projected_ER','ER']]:[];
$('detailStats').innerHTML=stats.length?'<table><thead><tr><th>Season</th>'+stats.map(([,label])=>'<th>'+esc(label)+'</th>').join('')+'</tr></thead><tbody>'+[[r.season+' projection','projected_'],[r.actual_season+' actual','actual_']].map(([label,prefix])=>'<tr><td>'+esc(label)+'</td>'+stats.map(([k])=>'<td>'+esc(fmt(k,r[k.replace('projected_',prefix)]))+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'<p class="missing">No player/role forecast in the established MLB process-stat model.</p>';
const historyRole=r.model_role||rows.find(p=>p.mlbam_id===r.mlbam_id&&p.model_role)?.model_role;const historyStats=historyRole==='Hitter'?hit:pitch;
const historical=rows.filter(p=>p.mlbam_id===r.mlbam_id&&p.season<meta.projection_season&&p.model_role!=null&&(p.model_role==='Hitter')===(historyRole==='Hitter')).sort((a,b)=>b.season-a.season);
$('historicalLines').innerHTML=historical.length?'<table><thead><tr><th>Season / line</th>'+historyStats.map(([,label])=>'<th>'+esc(label)+'</th>').join('')+'</tr></thead><tbody>'+historical.map(p=>[['Retrospective','projected_'],['Actual','actual_']].map(([label,prefix])=>'<tr><td>'+p.season+' '+label+' ('+p.model_role+')</td>'+historyStats.map(([k])=>'<td>'+esc(fmt(k,p[k.replace('projected_',prefix)]))+'</td>').join('')+'</tr>').join('')).join('')+'</tbody></table>':'<p class="note">No eligible pre-season forecast in the available historical windows.</p>';
$('detailStats').innerHTML+=r.model_role==='Hitter'?`<p class="note">OPS estimate = OBP (${fmt('projected_OPS',r.projected_OBP)}) + SLG (${fmt('projected_OPS',r.projected_SLG)}). All components are reconciled to the selected league environment. OPS before environment calibration: ${fmt('projected_OPS',r.unadjusted_projected_OPS)}. The contribution chart holds final denominators and estimated components fixed, so its environment bar is not the full before/after OPS change. Missing walks/HBP/sacrifices and doubles/triples use recent history with league shrinkage. Method: ${esc(r.ops_estimation_method)}. This is an estimate, not a separately fitted OPS model. Actual OPS is shown only when the supplemental source matches the displayed actual line.</p>`:r.model_role?'<p class="note">K% = K ÷ TBF; BB% = BB ÷ TBF; K−BB% = (K−BB) ÷ TBF. K−BB% is a percentage-point difference, not the K/BB ratio. Rates use the projected K and BB counts directly; WHIP is not needed. HR/TBF is a history-based estimate. Earned runs include a small historically fitted HR correction and league-budget reconciliation; total runs allowed include unearned runs at the league earned-run share.</p>':'';
const keys=['projection_coverage','source_season','sample_size','sample_size_type','effective_history_seasons','return_probability','projected_playing_time','chance_type','playing_time_method','save_assignment_required',...Object.keys(r).filter(k=>k.startsWith('roster_')&&!['roster_player_name','roster_contract_timeline'].includes(k))];
$('detailRows').innerHTML=keys.map(k=>{let value=esc(fmt(k,r[k]));if(k.endsWith('_url')&&/^https:\/\//.test(r[k]||''))value=`<a href="${esc(r[k])}" target="_blank" rel="noopener noreferrer">View source</a>`;return '<tr><td>'+esc(k.replace(/^roster_/,'').replaceAll('_',' '))+'</td><td>'+value+'</td></tr>';}).join('');
const terms=r.roster_contract_timeline?JSON.parse(r.roster_contract_timeline):[];$('timeline').innerHTML=terms.length?'<table><tr><th>Season</th><th>Term</th><th>Option status</th><th>Notes</th></tr>'+terms.map(t=>`<tr><td>${esc(t.term_season)}</td><td>${esc(t.term_type)}</td><td>${esc(t.option_status)}</td><td>${esc(t.option_notes)}</td></tr>`).join('')+'</table>':'No contract record available.';$('detail').showModal();}
['search','membership','team','position','role','depth','fa','options','coverage'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));
$('display').addEventListener('change',render);
const parkChoices=new Map();
function setupParkScenario(r){const active=Number(r.season)===2027&&['Hitter','SP','RP'].includes(r.model_role)&&r.park_scenarios_json;$('parkScenarioPanel').hidden=!active;if(!active)return;const choices=JSON.parse(r.park_scenarios_json);$('parkScenarioTeam').innerHTML='<option value="base">Published assignment</option>'+choices.map(s=>`<option value="${s.team_id}">${esc(s.team)}</option>`).join('');$('parkScenarioTeam').value=parkChoices.get(r.mlbam_id+':'+r.model_role)||'base';drawParkScenario();}
function drawParkScenario(){
 const r=detailPlayer;if(!r?.park_scenarios_json)return;
 const id=$('parkScenarioTeam').value;parkChoices.set(r.mlbam_id+':'+r.model_role,id);
 const s=JSON.parse(r.park_scenarios_json).find(x=>String(x.team_id)===id),pit=r.model_role!=='Hitter';
 const base=pit?{HRA:r.projected_HRA,HR_TBF:r.projected_HR_TBF_pct,ER:r.projected_ER,ERA:r.projected_ERA,RA:r.projected_RA,RA9:r.projected_RA9}:{HR:r.projected_HR,HR_PA:100*r.projected_HR/r.projected_PA,SLG:r.projected_SLG,OPS:r.projected_OPS};
 const columns=pit?[['HRA','HR allowed',2],['HR_TBF','HR/TBF',2,'%'],['ER','ER',2],['ERA','ERA',2],['RA','Runs allowed',2],['RA9','RA/9',2]]:[['HR','HR',2],['HR_PA','HR/PA',2,'%'],['SLG','SLG',3],['OPS','OPS',3]];
 $('parkScenarioVenue').textContent=s?s.park+' · hypothetical assignment':(r.roster_team_name||'Unassigned')+' · published projection';
 const data=[['Published',base],...(s?[[s.team,s]]:[])],event=pit?'HRA':'HR';
 $('parkScenarioStats').innerHTML='<table><thead><tr><th>Assignment</th>'+columns.map(c=>'<th>'+c[1]+'</th>').join('')+'<th>HR change</th></tr></thead><tbody>'+data.map(([name,v])=>`<tr><td>${esc(name)}</td>${columns.map(([key,label,digits,suffix])=>`<td>${v[key].toFixed(digits)}${suffix||''}</td>`).join('')}<td>${(v[event]-base[event]>=0?'+':'')+(v[event]-base[event]).toFixed(2)}</td></tr>`).join('')+'</tbody></table>';
 $('parkScenarioNote').textContent=(pit?'2027 published pitcher projections include park adjustments using allowed contact buckets, with batter handedness pooled. The prior three seasons’ bucket mix is shrunk toward league mix. HR allowed changes flow through the existing empirical HR-to-ER slope and earned-run share. IP, TBF, hits allowed, WHIP, K and BB stay fixed. The same bucket method drives this comparison; separate pitcher retrospective validation is still pending. ':'2027 hitter park-only scenario. HR, SLG and OPS change; hits, workload and other projections stay fixed. ')+"Half home / half neutral road. Saved roster, published projections and contribution chart stay fixed; scenarios do not rebalance the league. Kansas City uses its 2026 wall configuration.";
}
$('parkScenarioTeam').onchange=drawParkScenario;$('parkScenarioReset').onclick=()=>{$('parkScenarioTeam').value='base';drawParkScenario();};
function drawExplanation(){const r=detailPlayer;if(!r)return;const target=$('explainOutcome').value,e=explanations[`${r.mlbam_id}:${r.model_role}:${r.season}`]?.[target];if(!e)return;
const features=[...e.features.filter(f=>f.kind==='skill').sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution)),...e.features.filter(f=>f.kind!=='skill')];
let running=e.baseline;const bars=features.map(f=>{const start=running;running+=f.contribution;return {...f,start,end:running};});
const low=Math.min(e.baseline,e.final,...bars.flatMap(b=>[b.start,b.end])),high=Math.max(e.baseline,e.final,...bars.flatMap(b=>[b.start,b.end]));const pad=Math.max((high-low)*.18,Math.abs(e.final)*.02,.0001);const min=low-pad,max=high+pad,x=v=>340+(v-min)/(max-min)*420;
const format=v=>v.toFixed(['AVG','OPS'].includes(target)?4:['ERA','WHIP'].includes(target)?3:2),height=110+bars.length*57;
let svg=`<svg viewBox="0 0 880 ${height}" role="img" aria-label="Contribution waterfall for projected ${esc(target)}"><text x="12" y="24" fill="#e8f0f6" font-size="19" font-weight="650">Projected ${esc(target)}: ${format(e.final)}</text><text x="12" y="49" fill="#a5bdd0" font-size="12">Gold raises the number · Teal lowers it · Model contributions, not causal effects</text><line x1="${x(e.baseline)}" x2="${x(e.baseline)}" y1="70" y2="${height-32}" stroke="#a5bdd0" stroke-dasharray="4 4"/><text x="${x(e.baseline)}" y="68" text-anchor="middle" fill="#e8f0f6" font-size="11">Baseline ${format(e.baseline)}</text>`;
bars.forEach((b,i)=>{const y=86+i*57,color=b.contribution>=0?'#f2c94c':'#00c9e8',left=Math.min(x(b.start),x(b.end)),width=Math.max(Math.abs(x(b.end)-x(b.start)),1),value=(b.contribution>=0?'+':'')+format(b.contribution);const def=skillDefs.find(d=>d.stat===b.feature&&d.role===(r.model_role==='Hitter'?'Hitter':'Pitcher'));const sub=b.feature==='pulled_fb_forecast'?`${r.season} preseason forecast: ${b.latest_input_value==null?'unavailable':b.latest_input_value.toFixed(2)+' %'}`:b.kind==='skill'?(b.latest_input_value==null?'Latest input missing; season-median imputation':`${e.source_season} input: ${b.latest_input_value.toFixed(2)} ${def?.unit||''}`):b.feature==='league_environment'?'Selected league context and coherent event totals':b.feature==='ops_history_components'?'History-based components after environment calibration':b.feature==='calibration_pool'?'Combined adjustment after the base skill/history fit':'Historical model adjustment';
svg+=`<text x="12" y="${y+13}" fill="#e8f0f6" font-size="12" font-weight="600">${esc(b.label)}</text><text x="12" y="${y+30}" fill="#94adc3" font-size="11">${esc(sub)}</text><rect x="${left}" y="${y}" width="${width}" height="25" rx="4" fill="${color}"><title>${esc(b.label)}: ${value} ${esc(target)}</title></rect><text x="${Math.min(820,Math.max(x(b.start),x(b.end))+7)}" y="${y+18}" fill="#fff" font-size="12">${value}</text>`;
if(i<bars.length-1)svg+=`<line x1="${x(b.end)}" x2="${x(b.end)}" y1="${y+25}" y2="${y+57}" stroke="#839bae"/>`;});
svg+=`<text x="12" y="${height-8}" fill="#e8f0f6" font-size="12">Baseline + contributions = ${format(e.final)} ${esc(target)}</text></svg>`;svg=svg.replaceAll(esc(target),esc(outcomeLabel(target)));$('waterfall').innerHTML=svg;
$('explainNote').textContent=`Skill bars use measurements from ${e.history_seasons}, standardized against each season’s role median and passed through fitted skill/history coefficients. Latest input values are shown for context; bars incorporate the full history. Baseline is the model at median skill with this player's history structure and projected workload (${e.projected_workload.toFixed(1)} ${e.workload_unit}), not a league-average player. Age and limited-history regression are separate. Calibration, constraints and pool allocation are combined in the final adjustment.${e.denominator?' Ratio explanation holds final '+e.denominator.replace('projected_','')+' fixed at '+e.denominator_value.toFixed(2)+'.':''} Positive means a higher numerical outcome; for ERA and WHIP, lower is favorable. Historical skill bars use the original outcome model. When present, the Projected pulled FB% bar is the added preseason forecast adjustment; its rate recalibration and league-budget correction are shown separately.`;
if(target.endsWith('_pct'))$('explainNote').textContent+=' Bars are percentage-point contributions at fixed projected TBF. They do not attribute changes in TBF to skills.';
if(target==='HRA'||target==='HR_TBF_pct')$('explainNote').textContent='HR allowed uses three seasons of HR/TBF history normalized to each season, 3:2:1 recency weights, and a 500-TBF league prior. The baseline assigns league HR in proportion to projected hits allowed. League reconciliation makes total pitcher HR allowed equal total hitter HR, including anonymous newcomers. Published 2027 estimates also translate the pitcher’s allowed batted-ball buckets from prior park exposure to the assigned park, pooling batter handedness within each park/bucket. Park and league-budget contributions are shown separately.';
if(target==='OPS')$('explainNote').textContent+=' OPS holds projected AB and the OBP denominator fixed. Skill bars combine the modeled H and HR pathways. The separate history-components bar adds the estimated BB/HBP and doubles/triples terms; these are not fitted skill effects. Those component estimates and denominators are not varied in this explanation.';
}
$('projectedSeason').addEventListener('change',render);
$('explainOutcome').addEventListener('change',drawExplanation);
$('reset').onclick=()=>{['search','membership','team','position','role','depth','fa','options','coverage'].forEach(id=>$(id).value='');view='all';document.querySelectorAll('[data-view]').forEach(b=>b.className=b.dataset.view===view?'active':'secondary');render();};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.className=x===b?'active':'secondary');render();});
$('head').onclick=e=>{const key=e.target.closest('[data-key]')?.dataset.key;if(key){sortDir=sortKey===key?-sortDir:1;sortKey=key;render();}};
$('body').onclick=e=>{const cell=e.target.closest('[data-player]');if(cell)detail(Number(cell.dataset.player));};
$('body').onkeydown=e=>{if(e.key==='Enter'&&e.target.dataset.player!=null)detail(Number(e.target.dataset.player));};$('close').onclick=()=>$('detail').close();
$('csv').onclick=()=>{const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))].filter(k=>!k.startsWith('_'));const quote=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const text=[keys.map(quote).join(','),...filtered.map(r=>keys.map(k=>quote(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='roster_projections_'+$('projectedSeason').value+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
render();

document.addEventListener("click",e=>{const a=e.target.closest("a[href]");if(a&&/\.(parquet|json)$/.test(a.getAttribute("href"))){e.preventDefault();window.parent.dashboardDownload(a.getAttribute("href")).catch(error=>alert(error.message));}});
