
'use strict';
let DATA;
try {
 if(window.parent===window || typeof window.parent.skillGradesLoad!=='function')throw Error('Open the Projections page and sign in to view skill grades.');
 DATA=await window.parent.skillGradesLoad();
} catch(error) {
 const main=document.querySelector('main');main.replaceChildren();
 const message=document.createElement('p');message.textContent=error.message;main.appendChild(message);
 const link=document.createElement('a');link.href='./#skills';link.target='_top';link.textContent='Open Roster Atlas projections';main.appendChild(link);
 throw error;
}
const $=id=>document.getElementById(id), finite=x=>typeof x==='number'&&Number.isFinite(x), fmt=x=>!finite(x)?'—':Math.abs(x)<.05?'0.0':`${x>0?'+':''}${x.toFixed(1)}`;
const cats={Hitter:['Power','Speed','AVG'],Pitcher:['K','ERA','WHIP']}, loads={Hitter:600,SP:175,RP:60,Swingman:100};
const standardizedModel=DATA.standardized_model||DATA.metadata?.standardized_model||null;
function setText(id,text){if($(id))$(id).textContent=text}
if(standardizedModel){
 $('view').value='quality';
 setText('grade-reference','Higher is better in every category, including ERA and WHIP. Rate quality is forecast directly in standardized units. +1.0 means one MLB outcome SD above the assumed 2027 league level. Sum adds the three unrounded category grades with equal weight; it is a combined skill score, not standings points. A missing category leaves Sum unavailable.');
 setText('quality-reference','Rate quality is the primary forecast in category SD units. The 2027 league mean and spread use the preceding three seasons with the category’s selected recency weights. Contribution also accounts for comparison workloads: excess hits for AVG, earned runs prevented for ERA, baserunners prevented for WHIP, and category totals for HR, SB and K. Filtering, park selection, and role overrides do not redefine the league environment.');
 setText('speed-description','Speed forecasts MLB-equivalent SB rate from the stabilized process profile. It is a fantasy output skill, not a pure running-speed measurement. R, RBI, wins and saves are deferred.');
 setText('outcome-range-description','Historical ranges summarize residuals against regressed, park-neutral outcome targets, expressed in the assumed 2027 rate environment. They are not calibrated intervals for actual future outcomes, season-to-season luck, or uncertainty about underlying skill. Small changes in point grades should not be treated as certain differences.');
 setText('population-reference','Roster context is the configured October 3, 2026 snapshot. Players without a projected MLB role use neutral park when Current home park is selected. Choose a named park to explore a move. Minor-league profiles do not enter the MLB environment population. Missing calendar inputs retain their category weights through translated AAA and AA baselines, which add no observed playing time. Profiles without usable observed input evidence remain unavailable.');
 setText('validation-description',standardizedModel.evaluation?.description||'MASE and NRMSE compare forecasts with regressed, park-neutral future outcomes, using harmonic actual playing-time weights and 200 AB / 40 IP minimums. Historical folds use only earlier information. Rolling selection errors are out of sample; errors for the final 2027 weights across the same history are retrospective. Overall rows pool the entire player-season sample. Lower is better.');
}
const overrides=new Map();let selected=null, displayed=[], page=0;const pageSize=100;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=p=>`${p.mlbid}:${p.kind}`;
function role(p){return overrides.get(key(p))||p.assigned_role}
function rates(p,park){const r={...p.rates};if(park==='neutral'||(park==='current'&&!p.team_id&&!p.on_roster))return r;const id=park==='current'?p.team_id:park,f=p.parks[String(id)]||DATA.park_priors?.[p.kind]?.[String(id)];if(!f)return null;
if(finite(r.HR_rate)&&finite(r.H_rate)){const hr=r.HR_rate,nh=r.H_rate-hr;r.HR_rate=hr*f.HR;r.H_rate=r.HR_rate+nh*f.NH;if(p.kind==='Pitcher'&&finite(r.ER_rate))r.ER_rate=Math.max(0,r.ER_rate+DATA.run_weights.HR*(r.HR_rate-hr)+DATA.run_weights.NH*(nh*f.NH-nh))}return r}
function category(r,c){if(!r)return null;switch(c){case'Power':return r.HR_rate;case'Speed':return r.SB_rate;case'AVG':return r.H_rate;case'K':return r.K_rate;case'ERA':return finite(r.ER_rate)?9*r.ER_rate:null;case'WHIP':return finite(r.H_rate)&&finite(r.BB_rate)?r.H_rate+r.BB_rate:null}}
function rateScale(c){const environment=standardizedModel?.environment?.[c],s=DATA.standards[c];return {mean:finite(environment?.mean)?environment.mean:s.rate_mean,sd:finite(environment?.sd)?environment.sd:s.rate_sd}}
function calc(rate,c,workload,view){if(!finite(rate))return null;const s=DATA.standards[c];if(view==='quality'){const scale=rateScale(c);return scale.sd>0?(['ERA','WHIP'].includes(c)?-1:1)*(rate-scale.mean)/scale.sd:null}if(!finite(workload))return null;let value;if(['Power','Speed','K'].includes(c))value=rate*workload;else if(c==='AVG')value=(rate-s.reference_rate)*workload;else value=(s.reference_rate-rate)*workload/(c==='ERA'?9:1);return(value-s.contribution_mean)/s.contribution_sd}
function value(p,c,park=$('park').value,view=$('view').value){if(c==='Sum'){const values=cats[p.kind].map(category=>value(p,category,park,view));return values.every(finite)?values.reduce((a,b)=>a+b,0):null}if(standardizedModel&&view==='quality'&&finite(p.category_standardized?.[c])){const z=p.category_standardized[c],neutral=park==='neutral'||(park==='current'&&!p.team_id&&!p.on_roster);if(neutral)return z;const base=category(rates(p,'neutral'),c),scenario=category(rates(p,park),c),scale=rateScale(c);return finite(base)&&finite(scenario)&&scale.sd>0?z+(['ERA','WHIP'].includes(c)?-1:1)*(scenario-base)/scale.sd:null}return calc(category(rates(p,park),c),c,loads[role(p)],view)}
function compareGrades(a,b,column,direction){const av=value(a,column),bv=value(b,column);if(!finite(av)||!finite(bv))return finite(av)?-1:finite(bv)?1:a.player_name.localeCompare(b.player_name);return(direction==='asc'?av-bv:bv-av)||a.player_name.localeCompare(b.player_name)}
function benchmarkRate(c,z,workload,view){const s=DATA.standards[c],sign=['ERA','WHIP'].includes(c)?-1:1;if(view==='quality'){const scale=rateScale(c);return scale.mean+sign*z*scale.sd}const contribution=s.contribution_mean+z*s.contribution_sd;if(['Power','Speed','K'].includes(c))return contribution/workload;if(c==='AVG')return s.reference_rate+contribution/workload;return s.reference_rate-contribution*(c==='ERA'?9:1)/workload}
function statText(rate,c,workload){if(!finite(rate)||!finite(workload))return 'Unavailable';if(['Power','Speed','K'].includes(c))return (rate*workload).toFixed(0)+' '+({Power:'HR',Speed:'SB',K:'K'})[c];if(c==='AVG')return rate.toFixed(3).replace(/^0/,'')+' AVG';return rate.toFixed(c==='WHIP'?3:2)+' '+c}
function color(x){return finite(x)?x>=0?'good':'bad':''}
function setSort(){const old=$('sort').value,columns=[...cats[$('kind').value],'Sum'];$('sort').innerHTML=columns.map(c=>`<option>${c}</option>`).join('');$('sort').value=columns.includes(old)?old:'Sum'}
function render(){const kind=$('kind').value,q=$('search').value.trim().toLowerCase(),sort=$('sort').value;
displayed=DATA.players.filter(p=>p.kind===kind&&($('population').value==='all'||($('population').value==='roster'?p.on_roster:!p.on_roster&&p.minor_history_sample>0))&&(!q||p.player_name.toLowerCase().includes(q)||String(p.mlbid).includes(q)));
displayed.sort((a,b)=>compareGrades(a,b,sort,$('order').value));
if(!displayed.some(p=>key(p)===selected))selected=displayed.length?key(displayed[0]):null;
$('count').textContent=`${displayed.length.toLocaleString()} ${displayed.length===1?'profile':'profiles'} · ${$('view').selectedOptions[0].text} · ${$('park').selectedOptions[0].text}`;
$('head').innerHTML=`<tr><th>Player</th><th>Role / workload</th>${[...cats[kind],'Sum'].map(c=>`<th class="number" aria-sort="${sort===c?$('order').value==='asc'?'ascending':'descending':'none'}"><button type="button" data-sort="${c}" title="Sort by ${c}; click again to reverse order">${c}${sort===c?$('order').value==='asc'?' ↑':' ↓':''}</button></th>`).join('')}</tr>`;
document.querySelectorAll('#head button[data-sort]').forEach(button=>button.addEventListener('click',()=>{if($('sort').value===button.dataset.sort)$('order').value=$('order').value==='asc'?'desc':'asc';else{$('sort').value=button.dataset.sort;$('order').value='desc'}render()}));
page=Math.max(0,Math.min(page,Math.ceil(displayed.length/pageSize)-1));const pageRows=displayed.slice(page*pageSize,(page+1)*pageSize);$('pageStatus').textContent=`${displayed.length? page*pageSize+1:0}–${Math.min((page+1)*pageSize,displayed.length)} of ${displayed.length.toLocaleString()}`;$('previousPage').disabled=page===0;$('nextPage').disabled=(page+1)*pageSize>=displayed.length;
$('rows').innerHTML=pageRows.map(p=>`<tr data-key="${key(p)}" class="${key(p)===selected?'active':''}" tabindex="0"><td>${esc(p.player_name)}<div class="meta">${esc(p.team)}</div></td><td>${esc(role(p))}<div class="meta">${loads[role(p)]||'—'} ${kind==='Hitter'?'AB':'IP'}</div></td>${[...cats[kind],'Sum'].map(c=>{const x=value(p,c);return`<td class="number ${color(x)}">${fmt(x)}</td>`}).join('')}</tr>`).join('');
document.querySelectorAll('#rows tr').forEach(tr=>{const choose=()=>{selected=tr.dataset.key;render()};tr.addEventListener('click',choose);tr.addEventListener('keydown',e=>{if(e.key==='Enter')choose()})});renderDetail();}
function renderDetail(){const p=displayed.find(p=>key(p)===selected);if(!p){$('detail').innerHTML='<div class="empty">No matching players.</div>';return}const neutral=rates(p,'neutral'),scenario=rates(p,$('park').value),view=$('view').value,load=loads[role(p)],id=$('park').value==='current'?p.team_id:$('park').value;
let html=`<h2 class="playername">${esc(p.player_name)}</h2><div class="subline">${esc(p.team)} · ${esc(p.depth_role||p.assigned_role)}</div><span class="tag">Prior 3 seasons: ${Math.round(p.mlb_history_sample).toLocaleString()} MLB ${p.kind==='Hitter'?'AB':'IP'}</span>`;
html+=`<h2 style="margin-top:16px">Projected MLB-equivalent line</h2><p>${cats[p.kind].map(c=>esc(statText(category(scenario,c),c,load))).join(' · ')}</p><p class="note">At ${load||'—'} ${p.kind==='Hitter'?'AB':'IP'} · ${!p.team_id&&$('park').value==='current'&&!p.on_roster?'Neutral park (no projected MLB role)':esc($('park').selectedOptions[0].text)}. Standard-workload skill expectation, not expected actual playing time.</p>`;
if(standardizedModel)html+='<p class="note">These raw stats translate the standardized forecast through the assumed 2027 league environment, then apply the selected park. Each category uses its selected weights for the preceding three league means and spreads. In neutral park: rate = league mean + forecast SD × league SD; subtract for ERA and WHIP. Extreme rates may be bounded to keep a feasible stat line.</p>';
if(standardizedModel&&p.rate_bounds_applied&&Object.values(p.rate_bounds_applied).some(Boolean))html+='<p class="notice">Display bounds were applied to the stat line. The grade retains the standardized skill forecast; park changes add their rate effect to that same forecast. A bounded displayed stat may therefore not convert back to the displayed grade.</p>';
if(standardizedModel?.uncertainty&&typeof standardizedModel.uncertainty==='string')html+=`<p class="note">${esc(standardizedModel.uncertainty)}</p>`;
if(p.projection_status&&!['Available','Stabilized projection','Standardized projection'].includes(p.projection_status))html+=`<p class="notice">${esc(p.projection_status)}. Unavailable values are not zero.</p>`;
if(finite(p.surface_anchor_share)&&p.surface_anchor_share>0)html+=`<p class="note">${Math.round(p.surface_anchor_share*100)}% MiLB surface anchor. Inferred skills do not count as independent new evidence; the age adjustment comes afterward.</p>`;
if(p.stabilization)html+=`<p class="note">${esc(p.stabilization)}. Ballast is excluded from observed sample counts.</p>`;
if(p.sparse_input_policy&&!standardizedModel)html+=`<p class="note">${esc(p.sparse_input_policy)} Missing physical-input uncertainty is not fully captured by the sensitivity range.</p>`;
if(finite(p.projection_age))html+=`<div class="meta">Projection age: ${p.projection_age.toFixed(1)} · ${esc(p.age_source)}</div>`;
if(p.missing_season_inputs?.length)html+=`<div class="meta">Missing-season inputs: ${p.missing_season_inputs.map(s=>{const weights=s.weights?cats[p.kind].filter(c=>finite(s.weights[c])).map(c=>`${c} ${(100*s.weights[c]).toFixed(1)}%`).join(', '):finite(s.weight)?`${(100*s.weight).toFixed(1)}%`:'category weights shown in the model explainer';return `${s.season}: MLB-equivalent ${esc(s.level)} baseline (${weights})`}).join(' · ')}. No observed playing time added.</div>`;
if(p.last_input_season)html+=`<div class="meta">Latest input season: ${p.last_input_season}</div>`;
if(p.park_mix_source)html+=`<div class="meta">Park mix: ${esc(p.park_mix_source)}</div>`;
if(p.minor_history_sample>0)html+=`<div class="tag">${Math.round(p.minor_history_sample).toLocaleString()} minor-league ${p.kind==='Hitter'?'PA':'TBF'} included · ${Math.round(p.proxy_history_sample||0).toLocaleString()} from outcome-only records</div>`;
if(p.input_skills)html+=`<details><summary>Forecast process inputs and sources</summary><div class="scroll"><table><thead><tr><th>Input</th><th>Forecast</th><th>Source</th></tr></thead><tbody>${Object.entries(p.input_skills).filter(([k,v])=>finite(v)).map(([k,v])=>`<tr><td>${esc(({contact_vs_avg:'Contact vs expected',damage_rate:'Damage rate',EV90th:'EV90',z_con:'Zone contact',secondary_whiff_pct:'Secondary whiff',whiffs_vs_95:'Whiff vs 95+',SwStr:'Swinging strikes',Ball_pct:'Balls',Z_Contact:'Zone contact allowed'})[k]||k)}</td><td>${v.toFixed(1)}${k==='contact_vs_avg'?' pp':['EV90th','fastball_velo'].includes(k)?' mph':['SEAGER','stuff','grade_v13'].includes(k)?'':'%'}</td><td>${esc(DATA.input_source_labels?.[p.input_sources?.[k]]||p.input_sources?.[k]||'Forecast input; see methodology')}</td></tr>`).join('')}</tbody></table></div></details>`;
if(p.evidence_group==='Limited MLB history')html+='<p class="notice">Limited MLB history. Translated minor-league measurements and estimated inputs inform this profile. The pooled MLB outcome range is not calibrated for this evidence level.</p>';
if(p.kind==='Pitcher')html+=`<label>Workload role<select id="override"><option value="">Assigned: ${esc(p.assigned_role)}</option>${['SP','RP','Swingman'].map(r=>`<option ${overrides.get(key(p))===r?'selected':''}>${r}</option>`).join('')}</select></label><p class="note">${esc(p.role_source)}. Override changes workload, not rate skill.</p>`;
if($('park').value!=='neutral'&&!scenario)html+='<p class="notice">No current team is assigned. Select a neutral or named park to compare this player.</p>';
if(p.parks[String(id)]&&!p.parks[String(id)].supported)html+='<p class="notice">This park configuration lacks training observations; neutral factors are used.</p>';
for(const c of cats[p.kind]){const n=value(p,c,'neutral'),v=value(p,c),quality=value(p,c,'neutral','quality'),delta=finite(n)&&finite(v)?v-n:null;
const clipped=Math.max(-3,Math.min(3,v||0)),width=Math.abs(clipped)/6*100,left=clipped>=0?50:50-width;
html+=`<div class="grade-row"><div class="rowhead"><strong>${c}</strong><strong class="${color(v)}">${fmt(v)} SD</strong></div><div class="bartrack"><div class="bar" style="left:${left}%;width:${width}%;background:${clipped>=0?'var(--good)':'var(--bad)'}"></div></div><div class="breakdown"><span>Neutral ${fmt(n)}</span><span>Park Δ ${fmt(delta)}</span><span>Neutral quality ${fmt(quality)}</span></div>`;
html+=`<div class="note">Projected ${esc(statText(category(scenario,c),c,load))} · 0 SD: ${esc(statText(benchmarkRate(c,0,load,view),c,load))} · +1 SD: ${esc(statText(benchmarkRate(c,1,load,view),c,load))}</div>`;
const r=category(scenario,c),interval=DATA.intervals[c];if(finite(r)&&interval&&p.evidence_group!=='Limited MLB history'){const standardizedRange=standardizedModel&&view==='quality',sign=['ERA','WHIP'].includes(c)?-1:1,scale=rateScale(c),a=standardizedRange?v+sign*interval.low/scale.sd:calc(Math.max(0,r+interval.low),c,load,view),b=standardizedRange?v+sign*interval.high/scale.sd:calc(Math.max(0,r+interval.high),c,load,view);if(finite(a)&&finite(b))html+=`<div class="note">${standardizedModel?'Regressed-target residual range':'Historical outcome range'}: ${fmt(Math.min(a,b))} to ${fmt(Math.max(a,b))} SD</div>`}
const inputSD=p.input_uncertainty?.[c];if(finite(r)&&finite(inputSD)&&inputSD>0){const a=calc(Math.max(0,r-1.28*inputSD),c,load,view),b=calc(r+1.28*inputSD,c,load,view);if(finite(a)&&finite(b))html+=`<div class="note">Estimated-input sensitivity: ${fmt(Math.min(a,b))} to ${fmt(Math.max(a,b))} SD. Approximate; not a calibrated confidence interval.</div>`}
if(!finite(v))html+='<div class="note">Unavailable: insufficient skill measurements, unknown workload role, or no selected park.</div>';html+='</div>'}
html+='<p class="note">Bars span −3 to +3 SD; the numeric grade retains more extreme values. '+(standardizedModel?'Residual ranges refer to regressed targets and are not calibrated uncertainty for actual future outcomes or latent skill.':'Outcome ranges describe variability in future results, not certainty about underlying skill.')+'</p>';$('detail').innerHTML=html;
if($('override'))$('override').addEventListener('change',e=>{if(e.target.value)overrides.set(key(p),e.target.value);else overrides.delete(key(p));render()});}
for(const team of DATA.teams.slice().sort((a,b)=>a.name.localeCompare(b.name))){const o=document.createElement('option');o.value=team.id;o.textContent=`${team.name} · ${team.venue.name}`;$('park').appendChild(o)}
$('kind').addEventListener('change',()=>{setSort();render()});for(const id of ['population','park','view','sort','order'])$(id).addEventListener('change',render);$('search').addEventListener('input',render);
$('export').addEventListener('click',()=>{const rows=[['MLB ID','Player','Role','Standard workload','View','Park scenario',...cats[$('kind').value],'Sum'],...displayed.map(p=>[p.mlbid,p.player_name,role(p),loads[role(p)]??'',$('view').value,$('park').selectedOptions[0].text,...[...cats[p.kind],'Sum'].map(c=>{const v=value(p,c);return finite(v)?v.toFixed(1):''})])];const csv=rows.map(row=>row.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='fantasy_skill_grades.csv';a.click();URL.revokeObjectURL(url)});
function validationTable(rows){return '<div class="scroll"><table><thead><tr><th>Year / sample</th><th>Category</th><th>Player-seasons</th><th>MASE</th><th>NRMSE</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${esc(r.season??r.period??'Overall')}</td><td>${esc(r.category)}</td><td class="number">${esc(r.n??r.player_seasons??'—')}</td><td class="number">${finite(r.mase??r.MASE)?(r.mase??r.MASE).toFixed(4):'—'}</td><td class="number">${finite(r.nrmse??r.NRMSE)?((r.nrmse??r.NRMSE)*100).toFixed(2)+'%':'—'}</td></tr>`).join('')+'</tbody></table></div>'}
if(standardizedModel){
 const evaluation=standardizedModel.evaluation||{},season=evaluation.season_errors||evaluation.season_metrics||DATA.validation||[],overall=evaluation.overall_errors||evaluation.overall_metrics||[];
 $('validation').innerHTML='<h2>Rolling historical selection</h2>'+validationTable([...season,...overall]);
 const finalSeason=evaluation.final_weight_season_errors||[],finalOverall=evaluation.final_weight_overall_errors||[];
 if(finalSeason.length||finalOverall.length)$('validation').innerHTML+='<h2 style="margin-top:20px">Final 2027 weights on the same historical sample</h2><p class="note">Retrospective fit after selecting weights from all completed folds; this is not an independent test of the selected weights.</p>'+validationTable([...finalSeason,...finalOverall]);
}else $('validation').innerHTML='<table><thead><tr><th>Year</th><th>Category</th><th>Players</th><th>RMSE vs baseline</th><th>Rank correlation</th></tr></thead><tbody>'+(DATA.validation||[]).map(r=>`<tr><td>${r.season}</td><td>${r.category}</td><td>${r.n}</td><td>${((r.model_rmse/r.baseline_rmse-1)*100).toFixed(1)}%</td><td>${r.rank_correlation.toFixed(2)}</td></tr>`).join('')+'</tbody></table>';
$('previousPage').onclick=()=>{page--;render()};$('nextPage').onclick=()=>{page++;render()};for(const id of ['search','population','kind','park','view','sort','order'])$(id).addEventListener(id==='search'?'input':'change',()=>{page=0;render()});
setSort();render();

document.addEventListener('click',event=>{
 const link=event.target.closest('a[href]');
 if(!link)return;
 const path=link.getAttribute('href');
 if(['REPORT.md','player_grades.csv','manifest.json'].includes(path)){
  event.preventDefault();window.parent.skillGradesDownload(path).catch(error=>alert(error.message));
 }
});
