
'use strict';
let DATA;
try {
 if(window.parent===window || typeof window.parent.skillGradesLoad!=='function')throw Error('Open the Projections page and sign in to view skill grades.');
 DATA=await window.parent.skillGradesLoad();
 if(typeof window.parent.skillGradesWorkloadsLoad==='function'){
  const pt=await window.parent.skillGradesWorkloadsLoad();
  DATA.playing_time_model=pt.metadata;DATA.playing_time_standards=pt.standards;
  for(const p of DATA.players)p.playing_time=pt.players[`${p.mlbid}:${p.kind}`]||null;
 }
} catch(error) {
 const main=document.querySelector('main');main.replaceChildren();
 const message=document.createElement('p');message.textContent=error.message;main.appendChild(message);
 const link=document.createElement('a');link.href='./#skills';link.target='_top';link.textContent='Open Roster Atlas projections';main.appendChild(link);
 throw error;
}
const $=id=>document.getElementById(id), finite=x=>typeof x==='number'&&Number.isFinite(x), fmt=x=>!finite(x)?'—':Math.abs(x)<.05?'0.0':`${x>0?'+':''}${x.toFixed(1)}`;
const cats={Hitter:['Power','Speed','AVG'],Pitcher:['K','ERA','WHIP']}, loads={Hitter:600,SP:175,RP:60,Swingman:100};
const standardizedModel=DATA.standardized_model||DATA.metadata?.standardized_model||null;
function setText(id,text){if($(id))$(id).textContent=text}
if(standardizedModel){
 $('view').value=DATA.playing_time_model?'contribution':'quality';
 setText('grade-reference','Higher is better in every category, including ERA and WHIP. Rate quality is forecast directly in standardized units. +1.0 means one MLB outcome SD above the assumed 2027 league level. Sum adds the three unrounded category grades with equal weight; it is a combined skill score, not standings points. A missing category leaves Sum unavailable.');
 setText('quality-reference','Rate quality is the primary forecast in category SD units. The 2027 league mean and spread use the preceding three seasons with the category’s selected recency weights. Contribution also accounts for comparison workloads: excess hits for AVG, earned runs prevented for ERA, baserunners prevented for WHIP, and category totals for HR, SB and K. Filtering, park selection, and role overrides do not redefine the league environment.');
 setText('speed-description','Speed forecasts MLB-equivalent SB rate from the stabilized process profile. It is a fantasy output skill, not a pure running-speed measurement. R, RBI, wins and saves are deferred.');
 setText('outcome-range-description','Historical ranges summarize residuals against regressed, park-neutral outcome targets, expressed in the assumed 2027 rate environment. They are not calibrated intervals for actual future outcomes, season-to-season luck, or uncertainty about underlying skill. Small changes in point grades should not be treated as certain differences.');
 setText('population-reference','Roster context is the configured October 3, 2026 snapshot. Players without a projected MLB role use neutral park when Current home park is selected. Choose a named park to explore a move. Minor-league profiles do not enter the MLB environment population. Missing calendar inputs retain their category weights through translated AAA and AA baselines, which add no observed playing time. Profiles without usable observed input evidence remain unavailable.');
 setText('validation-description',standardizedModel.evaluation?.description||'MASE and NRMSE compare forecasts with regressed, park-neutral future outcomes, using harmonic actual playing-time weights and 200 AB / 40 IP minimums. Historical folds use only earlier information. Rolling selection errors are out of sample; errors for the final 2027 weights across the same history are retrospective. Overall rows pool the entire player-season sample. Lower is better.');
}
const overrides=new Map();let selected=null, displayed=[], page=0;const pageSize=100;
const modelHost=typeof window!=='undefined'&&window.parent!==window?window.parent:null;
let comparisonData=null,comparisonError='';
function rememberModelState(){if(modelHost?.skillGradesModel)modelHost.skillGradesState={selected,page,overrides:[...overrides],filters:Object.fromEntries(['kind','population','park','view','sort','order','search','workload','position'].map(id=>[id,$(id)?.value||'standard']))};}
function modelComparison(p){
 if(!modelHost?.skillGradesComparisonLoad)return '';
 if(!comparisonData)return '<p class="note">'+(comparisonError?esc(comparisonError):'Loading model comparison…')+'</p>';
 const models=[['original','Original live'],['research','Bayesian features']],workload=playerLoad(p),view=$('view').value,park=$('park').value;
 const values={};
 for(const [id] of models){const m=comparisonData[id],other=m.players[key(p)];values[id]={};if(!other)continue;
  const profile={...p,rates:other.rates},neutral=rates(profile,'neutral'),scenario=rates(profile,park);
  for(const c of cats[p.kind]){const raw=category(scenario,c),base=category(neutral,c),environment=m.environment[c],st=workloadMode()==='standard'?m.standards[c]:contributionStandard(c,id),sign=['ERA','WHIP'].includes(c)?-1:1;let z=null;
   if(view==='quality'&&finite(other.category_standardized?.[c])&&finite(raw)&&finite(base))z=other.category_standardized[c]+sign*(raw-base)/environment.sd;
   else if(view!=='quality'&&finite(raw)&&finite(workload)){let contribution;if(['Power','Speed','K'].includes(c))contribution=raw*workload;else if(c==='AVG')contribution=(raw-st.reference_rate)*workload;else contribution=(st.reference_rate-raw)*workload/(c==='ERA'?9:1);z=(contribution-st.contribution_mean)/st.contribution_sd;}
   values[id][c]={z,raw};
  }
 }
 let html='<h2 style="margin-top:20px">Model comparison</h2><p class="note">Same park and '+loadText(p)+' '+(p.kind==='Hitter'?'AB':'IP')+'. Δ is Bayesian minus original; positive favors the Bayesian grade. Each model translates through its own assumed 2027 environment.</p><div class="scroll"><table><thead><tr><th>Category</th><th>Original live</th><th>Bayesian features</th><th>Δ SD</th></tr></thead><tbody>';
 for(const c of [...cats[p.kind],'Sum']){const get=id=>c==='Sum'?{z:cats[p.kind].every(x=>finite(values[id][x]?.z))?cats[p.kind].reduce((sum,x)=>sum+values[id][x].z,0):null}:values[id][c]||{};const a=get('original'),b=get('research'),delta=finite(a.z)&&finite(b.z)?b.z-a.z:null;html+='<tr><td>'+c+'</td>'+[a,b].map(v=>'<td class="number">'+fmt(v.z)+' SD'+(c==='Sum'?'':'<br><small>'+esc(statText(v.raw,c,workload))+'</small>')+'</td>').join('')+'<td class="number '+color(delta)+'">'+fmt(delta)+'</td></tr>';}
 return html+'</tbody></table></div>';
}

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=p=>`${p.mlbid}:${p.kind}`;
function role(p){return overrides.get(key(p))||p.assigned_role}
function workloadMode(){return $('workload')?.value||'standard'}
function workloadVariant(p){const mode=workloadMode();if(mode==='standard'||!p.playing_time)return null;const method=mode==='projected'?p.playing_time.selected.replace(/_age$/,''):mode;return p.playing_time.variants[method]||null}
function playerLoad(p){if(overrides.has(key(p)))return loads[role(p)];const variant=workloadVariant(p);return variant?(p.kind==='Hitter'?variant.AB:variant.IP):workloadMode()==='standard'||!DATA.playing_time_model?loads[role(p)]:null}
function loadText(p){const n=playerLoad(p);return finite(n)?n.toFixed(p.kind==='Hitter'?0:1):'—'}
function contributionStandard(c,modelId){const mode=workloadMode(),id=modelId||modelHost?.skillGradesModel?.()||'original';return mode!=='standard'&&DATA.playing_time_standards?.[id]?.[mode]?.[c]||DATA.standards[c]}

function rates(p,park){const r={...p.rates};if(park==='neutral'||(park==='current'&&!p.team_id&&!p.on_roster))return r;const id=park==='current'?p.team_id:park,f=p.parks[String(id)]||DATA.park_priors?.[p.kind]?.[String(id)];if(!f)return null;
if(finite(r.HR_rate)&&finite(r.H_rate)){const hr=r.HR_rate,nh=r.H_rate-hr;r.HR_rate=hr*f.HR;r.H_rate=r.HR_rate+nh*f.NH;if(p.kind==='Pitcher'&&finite(r.ER_rate))r.ER_rate=Math.max(0,r.ER_rate+DATA.run_weights.HR*(r.HR_rate-hr)+DATA.run_weights.NH*(nh*f.NH-nh))}return r}
function category(r,c){if(!r)return null;switch(c){case'Power':return r.HR_rate;case'Speed':return r.SB_rate;case'AVG':return r.H_rate;case'K':return r.K_rate;case'ERA':return finite(r.ER_rate)?9*r.ER_rate:null;case'WHIP':return finite(r.H_rate)&&finite(r.BB_rate)?r.H_rate+r.BB_rate:null}}
function rateScale(c){const environment=standardizedModel?.environment?.[c],s=DATA.standards[c];return {mean:finite(environment?.mean)?environment.mean:s.rate_mean,sd:finite(environment?.sd)?environment.sd:s.rate_sd}}
function calc(rate,c,workload,view){if(!finite(rate))return null;const s=contributionStandard(c);if(view==='quality'){const scale=rateScale(c);return scale.sd>0?(['ERA','WHIP'].includes(c)?-1:1)*(rate-scale.mean)/scale.sd:null}if(!finite(workload))return null;let value;if(['Power','Speed','K'].includes(c))value=rate*workload;else if(c==='AVG')value=(rate-s.reference_rate)*workload;else value=(s.reference_rate-rate)*workload/(c==='ERA'?9:1);return(value-s.contribution_mean)/s.contribution_sd}
function value(p,c,park=$('park').value,view=$('view').value){if(c==='Sum'){const values=cats[p.kind].map(category=>value(p,category,park,view));return values.every(finite)?values.reduce((a,b)=>a+b,0):null}if(standardizedModel&&view==='quality'&&finite(p.category_standardized?.[c])){const z=p.category_standardized[c],neutral=park==='neutral'||(park==='current'&&!p.team_id&&!p.on_roster);if(neutral)return z;const base=category(rates(p,'neutral'),c),scenario=category(rates(p,park),c),scale=rateScale(c);return finite(base)&&finite(scenario)&&scale.sd>0?z+(['ERA','WHIP'].includes(c)?-1:1)*(scenario-base)/scale.sd:null}return calc(category(rates(p,park),c),c,playerLoad(p),view)}
function compareGrades(a,b,column,direction){const av=value(a,column),bv=value(b,column);if(!finite(av)||!finite(bv))return finite(av)?-1:finite(bv)?1:a.player_name.localeCompare(b.player_name);return(direction==='asc'?av-bv:bv-av)||a.player_name.localeCompare(b.player_name)}
function benchmarkRate(c,z,workload,view){const s=view==='quality'?DATA.standards[c]:contributionStandard(c),sign=['ERA','WHIP'].includes(c)?-1:1;if(view==='quality'){const scale=rateScale(c);return scale.mean+sign*z*scale.sd}const contribution=s.contribution_mean+z*s.contribution_sd;if(['Power','Speed','K'].includes(c))return contribution/workload;if(c==='AVG')return s.reference_rate+contribution/workload;return s.reference_rate-contribution*(c==='ERA'?9:1)/workload}
function statText(rate,c,workload){if(!finite(rate)||!finite(workload))return 'Unavailable';if(['Power','Speed','K'].includes(c))return (rate*workload).toFixed(0)+' '+({Power:'HR',Speed:'SB',K:'K'})[c];if(c==='AVG')return rate.toFixed(3).replace(/^0/,'')+' AVG';return rate.toFixed(c==='WHIP'?3:2)+' '+c}
function color(x){return finite(x)?x>=0?'good':'bad':''}
function setSort(){const old=$('sort').value,columns=[...cats[$('kind').value],'Sum'];$('sort').innerHTML=columns.map(c=>`<option>${c}</option>`).join('');$('sort').value=columns.includes(old)?old:'Sum'}
function eligiblePositions(p){return modelHost?.projectionEligiblePositions?.(p.mlbid,p.kind,2026)||[];}
function updatePositions(){const choices=new Set(DATA.players.filter(p=>p.kind===$('kind').value).flatMap(eligiblePositions)),previous=$('position').value;$('position').innerHTML='<option value="">All positions</option>'+(modelHost?.projectionPositionOptions||[]).filter(p=>choices.has(p)).map(p=>'<option value="'+p+'">'+p+'</option>').join('');$('position').value=choices.has(previous)?previous:'';setText('positionEligibilityNote',modelHost?.projectionPositionNote?.(2026)||'');}
function render(){updatePositions();const kind=$('kind').value,q=$('search').value.trim().toLowerCase(),sort=$('sort').value;
displayed=DATA.players.filter(p=>p.kind===kind&&(!$('position').value||eligiblePositions(p).includes($('position').value))&&($('population').value==='all'||($('population').value==='roster'?p.on_roster:!p.on_roster&&p.minor_history_sample>0))&&(!q||p.player_name.toLowerCase().includes(q)||String(p.mlbid).includes(q)));
displayed.sort((a,b)=>compareGrades(a,b,sort,$('order').value));
if(!displayed.some(p=>key(p)===selected))selected=displayed.length?key(displayed[0]):null;
$('count').textContent=`${displayed.length.toLocaleString()} ${displayed.length===1?'profile':'profiles'} · ${$('view').selectedOptions[0].text} · ${$('park').selectedOptions[0].text}`;
$('head').innerHTML=`<tr><th>Player</th><th>Role / workload</th>${[...cats[kind],'Sum'].map(c=>`<th class="number" aria-sort="${sort===c?$('order').value==='asc'?'ascending':'descending':'none'}"><button type="button" data-sort="${c}" title="Sort by ${c}; click again to reverse order">${c}${sort===c?$('order').value==='asc'?' ↑':' ↓':''}</button></th>`).join('')}</tr>`;
document.querySelectorAll('#head button[data-sort]').forEach(button=>button.addEventListener('click',()=>{if($('sort').value===button.dataset.sort)$('order').value=$('order').value==='asc'?'desc':'asc';else{$('sort').value=button.dataset.sort;$('order').value='desc'}render()}));
page=Math.max(0,Math.min(page,Math.ceil(displayed.length/pageSize)-1));const pageRows=displayed.slice(page*pageSize,(page+1)*pageSize);$('pageStatus').textContent=`${displayed.length? page*pageSize+1:0}–${Math.min((page+1)*pageSize,displayed.length)} of ${displayed.length.toLocaleString()}`;$('previousPage').disabled=page===0;$('nextPage').disabled=(page+1)*pageSize>=displayed.length;
$('rows').innerHTML=pageRows.map(p=>`<tr data-key="${key(p)}" class="${key(p)===selected?'active':''}" tabindex="0"><td>${esc(p.player_name)}<div class="meta">${esc(p.team)}</div></td><td>${esc(role(p))}<div class="meta">${loadText(p)} ${kind==='Hitter'?'AB':'IP'}</div></td>${[...cats[kind],'Sum'].map(c=>{const x=value(p,c);return`<td class="number ${color(x)}">${fmt(x)}</td>`}).join('')}</tr>`).join('');
document.querySelectorAll('#rows tr').forEach(tr=>{const choose=()=>{selected=tr.dataset.key;render()};tr.addEventListener('click',choose);tr.addEventListener('keydown',e=>{if(e.key==='Enter')choose()})});renderDetail();rememberModelState();}
function renderDetail(){const p=displayed.find(p=>key(p)===selected);if(!p){$('detail').innerHTML='<div class="empty">No matching players.</div>';return}const neutral=rates(p,'neutral'),scenario=rates(p,$('park').value),view=$('view').value,load=playerLoad(p),id=$('park').value==='current'?p.team_id:$('park').value;
let html=`<h2 class="playername">${esc(p.player_name)}</h2><div class="subline">${esc(p.team)} · ${esc(p.depth_role||p.assigned_role)}</div><div class="subline">Eligible positions: ${esc(eligiblePositions(p).join(' / ')||'No qualifying position')}</div><span class="tag">Prior 3 seasons: ${Math.round(p.mlb_history_sample).toLocaleString()} MLB ${p.kind==='Hitter'?'AB':'IP'}</span>`;
html+=`<h2 style="margin-top:16px">Projected MLB-equivalent line</h2><p>${cats[p.kind].map(c=>esc(statText(category(scenario,c),c,load))).join(' · ')}</p><p class="note">At ${loadText(p)} ${p.kind==='Hitter'?'AB':'IP'} · ${!p.team_id&&$('park').value==='current'&&!p.on_roster?'Neutral park (no projected MLB role)':esc($('park').selectedOptions[0].text)}. ${workloadMode()==='standard'?'Standard-workload skill expectation.':'History-based playing-time estimate; actual availability and roster decisions may differ.'}</p>`;
const pt=workloadVariant(p);
if(pt){html+='<p class="note"><strong>Projected playing time:</strong> '+(p.kind==='Hitter'?pt.PA.toFixed(0)+' PA · '+pt.AB.toFixed(0)+' AB':pt.IP.toFixed(1)+' IP')+' · '+esc(pt.configuration.replace(/_/g,' '))+' · recency '+pt.weights.map(w=>(w*100).toFixed(1)+'%').join(' / ')+'.</p>';if(overrides.has(key(p)))html+='<p class="notice">Manual role override uses the standard '+loads[role(p)]+' IP workload. Restore the assigned role to use projected innings.</p>';if(!p.on_roster)html+='<p class="notice">No projected MLB roster role is assigned. This is a workload estimate from translated history, not a guaranteed call-up or MLB opportunity.</p>';}
html+=modelComparison(p);
if(standardizedModel)html+='<p class="note">These raw stats translate the standardized forecast through the assumed 2027 league environment, then apply the selected park. Each category uses its selected weights for the preceding three league means and spreads. In neutral park: rate = league mean + forecast SD × league SD; subtract for ERA and WHIP. Extreme rates may be bounded to keep a feasible stat line.</p>';
if(standardizedModel&&p.rate_bounds_applied&&Object.values(p.rate_bounds_applied).some(Boolean))html+='<p class="notice">Display bounds were applied to the stat line. The grade retains the standardized skill forecast; park changes add their rate effect to that same forecast. A bounded displayed stat may therefore not convert back to the displayed grade.</p>';
if(standardizedModel?.uncertainty&&typeof standardizedModel.uncertainty==='string')html+=`<p class="note">${esc(standardizedModel.uncertainty)}</p>`;
if(p.projection_status&&!['Available','Stabilized projection','Standardized projection'].includes(p.projection_status))html+=`<p class="notice">${esc(p.projection_status)}. Unavailable values are not zero.</p>`;
if(finite(p.surface_anchor_share)&&p.surface_anchor_share>0)html+=`<p class="note">${Math.round(p.surface_anchor_share*100)}% MiLB surface anchor. Inferred skills do not count as independent new evidence; the age adjustment comes afterward.</p>`;
if(p.stabilization)html+=`<p class="note">${esc(p.stabilization)}. Ballast is excluded from observed sample counts.</p>`;
if(p.sparse_input_policy&&!standardizedModel)html+=`<p class="note">${esc(p.sparse_input_policy)} Missing physical-input uncertainty is not fully captured by the sensitivity range.</p>`;
if(finite(p.projection_age))html+=`<div class="meta">Projection age: ${p.projection_age.toFixed(1)} · ${esc(p.age_source)}</div>`;
if(p.missing_season_inputs?.length)html+=`<div class="meta">Missing-season inputs: ${p.missing_season_inputs.map(s=>{const weights=s.weights?cats[p.kind].filter(c=>finite(s.weights[c])).map(c=>`${c} ${(100*s.weights[c]).toFixed(1)}%`).join(', '):finite(s.weight)?`${(100*s.weight).toFixed(1)}%`:'category weights shown in the model explainer';return `${s.season}: MLB-equivalent ${esc(s.level)} baseline (${weights})`}).join(' · ')}. No observed playing time added.</div>`;
if(p.last_input_season)html+=`<div class="meta">Latest input season: ${p.last_input_season}</div>`;
if(p.park_mix_source)html+=`<div class="meta">Park mix: ${esc(p.park_mix_source)}</div>`;
if(p.minor_history_sample>0)html+=`<div class="tag">${Math.round(p.minor_history_sample).toLocaleString()} minor-league ${p.kind==='Hitter'?'PA':'TBF'} included · ${Math.round(p.proxy_history_sample||0).toLocaleString()} from outcome-only records</div>`;
if(p.input_skills)html+=`<details><summary>Forecast process inputs and sources</summary><div class="scroll"><table><thead><tr><th>Input</th><th>Forecast</th><th>Source</th></tr></thead><tbody>${Object.entries(p.input_skills).filter(([k,v])=>finite(v)).map(([k,v])=>`<tr><td>${esc(({contact_vs_avg:'Contact vs expected',damage_rate:'Damage rate',EV90th:'EV90',z_con:'Zone contact',secondary_whiff_pct:'Secondary whiff',whiffs_vs_95:'Whiff vs 95+',SwStr:'Swinging strikes',Ball_pct:'Balls',Z_Contact:'Zone contact allowed'})[k]||k)}</td><td>${v.toFixed(1)}${k==='contact_vs_avg'?' pp':['EV90th','fastball_velo'].includes(k)?' mph':['SEAGER','stuff','grade_v13'].includes(k)?'':'%'}</td><td>${esc(DATA.input_source_labels?.[p.input_sources?.[k]]||p.input_sources?.[k]||'Forecast input; see methodology')}</td></tr>`).join('')}</tbody></table></div></details>`;
if(p.additional_process_z)html+='<details><summary>Additional process inputs · annual SD units</summary><p class="note">Regressed annual standardized measurements blended with the K recency weights. Zero includes unmeasured MLB priors; these physical traits are not inferred from minor-league outcomes.</p><div class="scroll"><table><tbody>'+Object.entries(p.additional_process_z).map(([name,z])=>'<tr><td>'+esc(name.replace(/^extra_/,''))+'</td><td>'+fmt(z)+' SD</td></tr>').join('')+'</tbody></table></div></details>';
if(p.evidence_group==='Limited MLB history')html+='<p class="notice">Limited MLB history. Translated minor-league measurements and estimated inputs inform this profile. The pooled MLB outcome range is not calibrated for this evidence level.</p>';
if(p.kind==='Pitcher')html+=`<label>Workload role<select id="override"><option value="">Assigned: ${esc(p.assigned_role)}</option>${['SP','RP','Swingman'].map(r=>`<option ${overrides.get(key(p))===r?'selected':''}>${r}</option>`).join('')}</select></label><p class="note">${esc(p.role_source)}. Override uses the selected role’s standard workload; rate skill stays fixed.</p>`;
if($('park').value!=='neutral'&&!scenario)html+='<p class="notice">No current team is assigned. Select a neutral or named park to compare this player.</p>';
if(p.parks[String(id)]&&!p.parks[String(id)].supported)html+='<p class="notice">This park configuration lacks training observations; neutral factors are used.</p>';
for(const c of cats[p.kind]){const n=value(p,c,'neutral'),v=value(p,c),quality=value(p,c,'neutral','quality'),delta=finite(n)&&finite(v)?v-n:null;
const clipped=Math.max(-3,Math.min(3,v||0)),width=Math.abs(clipped)/6*100,left=clipped>=0?50:50-width;
html+=`<div class="grade-row"><div class="rowhead"><strong>${c}</strong><strong class="${color(v)}">${fmt(v)} SD</strong></div><div class="bartrack"><div class="bar" style="left:${left}%;width:${width}%;background:${clipped>=0?'var(--good)':'var(--bad)'}"></div></div><div class="breakdown"><span>Neutral ${fmt(n)}</span><span>Park Δ ${fmt(delta)}</span><span>Neutral quality ${fmt(quality)}</span></div>`;
html+=`<div class="note">Projected ${esc(statText(category(scenario,c),c,load))} · 0 SD: ${esc(statText(benchmarkRate(c,0,load,view),c,load))} · +1 SD: ${esc(statText(benchmarkRate(c,1,load,view),c,load))}</div>`;
const r=category(scenario,c),interval=DATA.intervals[c];if(finite(r)&&interval&&p.evidence_group!=='Limited MLB history'){const standardizedRange=standardizedModel&&view==='quality',sign=['ERA','WHIP'].includes(c)?-1:1,scale=rateScale(c),a=standardizedRange?v+sign*interval.low/scale.sd:calc(Math.max(0,r+interval.low),c,load,view),b=standardizedRange?v+sign*interval.high/scale.sd:calc(Math.max(0,r+interval.high),c,load,view);if(finite(a)&&finite(b))html+=`<div class="note">${standardizedModel?'Regressed-target residual range':'Historical outcome range'}: ${fmt(Math.min(a,b))} to ${fmt(Math.max(a,b))} SD</div>`}
const inputSD=p.input_uncertainty?.[c];if(finite(r)&&finite(inputSD)&&inputSD>0){const a=calc(Math.max(0,r-1.28*inputSD),c,load,view),b=calc(r+1.28*inputSD,c,load,view);if(finite(a)&&finite(b))html+=`<div class="note">Estimated-input sensitivity: ${fmt(Math.min(a,b))} to ${fmt(Math.max(a,b))} SD. Approximate; not a calibrated confidence interval.</div>`}
if(!finite(v))html+='<div class="note">Unavailable: insufficient skill measurements, unknown workload role, or no selected park.</div>';html+='</div>'}
html+='<p class="note">Bars span −3 to +3 SD; the numeric grade retains more extreme values. '+(standardizedModel?'Residual ranges refer to regressed targets and are not calibrated uncertainty for actual future outcomes or latent skill.':'Outcome ranges describe variability in future results, not certainty about underlying skill.')+'</p>';$('detail').innerHTML=html;
if($('override'))$('override').addEventListener('change',e=>{if(e.target.value)overrides.set(key(p),e.target.value);else overrides.delete(key(p));render()});}
for(const team of DATA.teams.slice().sort((a,b)=>a.name.localeCompare(b.name))){const o=document.createElement('option');o.value=team.id;o.textContent=`${team.name} · ${team.venue.name}`;$('park').appendChild(o)}
$('kind').addEventListener('change',()=>{setSort();render()});for(const id of ['population','park','view','sort','order','workload','position'])$(id)?.addEventListener('change',render);$('search').addEventListener('input',render);
$('export').addEventListener('click',()=>{const rows=[['MLB ID','Player','Role','Eligible positions','AB / IP workload','View','Park scenario',...cats[$('kind').value],'Sum'],...displayed.map(p=>[p.mlbid,p.player_name,role(p),eligiblePositions(p).join(' / '),playerLoad(p)??'',$('view').value,$('park').selectedOptions[0].text,...[...cats[p.kind],'Sum'].map(c=>{const v=value(p,c);return finite(v)?v.toFixed(1):''})])];const csv=rows.map(row=>row.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='fantasy_skill_grades.csv';a.click();URL.revokeObjectURL(url)});
function validationTable(rows){return '<div class="scroll"><table><thead><tr><th>Year / sample</th><th>Category</th><th>Player-seasons</th><th>MASE</th><th>NRMSE</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${esc(r.season??r.period??'Overall')}</td><td>${esc(r.category)}</td><td class="number">${esc(r.n??r.player_seasons??'—')}</td><td class="number">${finite(r.mase??r.MASE)?(r.mase??r.MASE).toFixed(4):'—'}</td><td class="number">${finite(r.nrmse??r.NRMSE)?((r.nrmse??r.NRMSE)*100).toFixed(2)+'%':'—'}</td></tr>`).join('')+'</tbody></table></div>'}
if(standardizedModel){
 const evaluation=standardizedModel.evaluation||{},season=evaluation.season_errors||evaluation.season_metrics||DATA.validation||[],overall=evaluation.overall_errors||evaluation.overall_metrics||[];
 $('validation').innerHTML='<h2>Rolling historical selection</h2>'+validationTable([...season,...overall]);
 const finalSeason=evaluation.final_weight_season_errors||[],finalOverall=evaluation.final_weight_overall_errors||[];
 if(finalSeason.length||finalOverall.length)$('validation').innerHTML+='<h2 style="margin-top:20px">Final 2027 weights on the same historical sample</h2><p class="note">Retrospective fit after selecting weights from all completed folds; this is not an independent test of the selected weights.</p>'+validationTable([...finalSeason,...finalOverall]);
}else $('validation').innerHTML='<table><thead><tr><th>Year</th><th>Category</th><th>Players</th><th>RMSE vs baseline</th><th>Rank correlation</th></tr></thead><tbody>'+(DATA.validation||[]).map(r=>`<tr><td>${r.season}</td><td>${r.category}</td><td>${r.n}</td><td>${((r.model_rmse/r.baseline_rmse-1)*100).toFixed(1)}%</td><td>${r.rank_correlation.toFixed(2)}</td></tr>`).join('')+'</tbody></table>';
$('previousPage').onclick=()=>{page--;render()};$('nextPage').onclick=()=>{page++;render()};for(const id of ['search','population','kind','park','view','sort','order','workload','position'])$(id)?.addEventListener(id==='search'?'input':'change',()=>{page=0;render()});

if(DATA.playing_time_model){
 const pt=DATA.playing_time_model;
 setText('workload-reference','Projected playing time uses actual three-year workloads, translated at each minor-league level, with ordered recency weights selected from historical tests. The Playing time selector also offers an ordered full-season ballast comparison and the original standard workloads. Rate quality isolates skill; fantasy contribution includes the chosen volume.');
 setText('grade-reference','Higher is better in every category. Projected contribution uses forecast PA/IP and a fixed projected MLB-role reference population. Rate quality isolates the standardized skill forecast. Sum adds the three category grades with equal weight, not standings points.');
 setText('quality-reference','Rate quality stays in the core model’s category SD units. Projected contribution uses HR/SB/K totals and volume-weighted excess hits, earned runs prevented, or baserunners prevented. Each core model and playing-time method has a fixed MLB-role benchmark; minor-league-only profiles and filters do not redefine it. Standard workload restores the prior 600 AB / role IP convention.');
 $('playing-time-explainer').hidden=false;
 const scopes={harmonic_positive:'Harmonic · nonzero MLB',all_players:'All prior players · includes zero MLB',zero_mlb:'Zero MLB only · NRMSE undefined'};
 let html='<p class="note">'+esc(pt.target_policy)+'</p><p class="note">'+esc(pt.weighting)+'</p><p class="note">'+esc(pt.metric_definition)+'</p><p class="note">'+esc(pt.selection)+'</p><p class="note">'+esc(pt.missing_policy)+'</p><p class="note">'+esc(pt.age)+'</p><p class="note">'+esc(pt.limitations)+'</p>';
 html+='<p class="note">Ballast full-season targets are 600 PA for hitters, 175 IP for SP, 60 IP for RP, and 100 IP for swingmen. The standard skill comparison continues to use 600 AB for hitters. Exact requested ballast = (sum of three actual translated workloads + weighted full-season shortfalls) / 3. Its actual-season coefficients are (1 − weight) / 3, so higher deficit recency gives lower actual-season influence. Ordered ballast = weighted workload + one-third of its full-season shortfall; this preserves newest > middle > oldest.</p><h2>Final playing-time choices</h2><div class="scroll"><table><thead><tr><th>Role</th><th>Method</th><th>Selected</th><th>n / n−1 / n−2</th><th>Age</th></tr></thead><tbody>';
 for(const [r,choices] of Object.entries(pt.by_method))for(const [method,name] of Object.entries(choices)){const c=pt.configurations[r][name];html+='<tr><td>'+r+'</td><td>'+esc(method.replace(/_/g,' '))+'</td><td>'+(pt.selected[r]===name?'Yes':'')+'</td><td>'+c.weights.map(w=>(w*100).toFixed(1)+'%').join(' / ')+'</td><td>'+(c.age?'Yes':'No')+'</td></tr>';}
 html+='</tbody></table></div><h2>Pooled chronological playing-time errors</h2><p class="note">Targets are actual unregressed MLB PA/IP. MAE and RMSE are PA for hitters and IP for pitchers. MASE and NRMSE are dimensionless. Positive bias overpredicts. Recency and age fits use earlier information; the displayed method/age choices use all completed folds and are not an independent holdout.</p>';
 const table=rows=>'<div class="scroll"><table><thead><tr><th>Role</th><th>Method / season</th><th>Scope</th><th>N</th><th>Zero MLB</th><th>MAE</th><th>RMSE</th><th>MASE</th><th>NRMSE</th><th>Bias</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+r.role+'</td><td>'+esc(r.season??r.configuration)+'</td><td>'+esc(scopes[r.scope])+'</td><td>'+r.n+'</td><td>'+r.zero_mlb+'</td>'+['mae','rmse','mase','nrmse','bias'].map(k=>'<td class="number">'+(finite(r[k])?r[k].toFixed(k==='mase'||k==='nrmse'?3:1):'—')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
 html+=table(pt.overall_errors.filter(r=>Object.values(pt.by_method[r.role]).includes(r.configuration)));
 html+='<details><summary>Season-specific errors · selected configurations</summary>'+table(pt.seasonal_errors.filter(r=>pt.selected[r.role]===r.configuration))+'</details><p><a href="playing_time/REPORT.md">Playing-time report</a> · <a href="playing_time/forecast_totals.csv">Projected totals CSV · both models</a> · <a href="playing_time/season_errors.csv">Season errors CSV</a> · <a href="playing_time/overall_errors.csv">Pooled errors CSV</a></p>';
 $('playing-time-methodology').innerHTML=html;
}
const savedState=modelHost?.skillGradesState;
updatePositions();
if(savedState){for(const [id,v] of Object.entries(savedState.filters))if(id!=='sort'&&$(id))$(id).value=v;selected=savedState.selected;page=savedState.page||0;for(const [id,r] of savedState.overrides||[])overrides.set(id,r);}
setSort();if(savedState?.filters.sort)$('sort').value=savedState.filters.sort;render();
if(modelHost?.skillGradesComparisonLoad)modelHost.skillGradesComparisonLoad().then(data=>{comparisonData=data;renderDetail();}).catch(error=>{comparisonError='Comparison unavailable: '+error.message;renderDetail();});

document.addEventListener('click',event=>{
 const link=event.target.closest('a[href]');
 if(!link)return;
 const path=link.getAttribute('href');
 if(['REPORT.md','player_grades.csv','manifest.json','playing_time/REPORT.md','playing_time/season_errors.csv','playing_time/overall_errors.csv','playing_time/forecast_totals.csv'].includes(path)){
  event.preventDefault();window.parent.skillGradesDownload(path).catch(error=>alert(error.message));
 }
});
